name: flash_message
description: "Clean and simple flash messages for Flutter with multiple styles and easy positioning. Zero dependencies."
version: 0.0.1
homepage: https://github.com/Penguin5681/Flash-Message

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
